# -*- coding: utf-8 -*-
"""meriskills.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19s8PgtFNuaG9Sx6rqeyFEVA2ruCEKT9Y
"""

import pandas as pd
import numpy as np
import matplotlib. pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

file_path = "/content/drive/MyDrive/diabetes (1).csv"
data = pd.read_csv(file_path)
print(data)

sns. heatmap(data. isnull( ) )

correlation =data.corr()
print (correlation)

X =data.drop("outcome",axis=1)
Y =data[ 'outcome']
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,test_size=0.2)

model=LogisticRegression()
model.fit(X_train,Y_train)

prediction = model.predict(X_test)
print(prediction)